### ISSUE TITLE
Transform fairseq model to huggingface's transformers model

### ISSUE THREAD

**Issue by pooruss** [THU-KEG/KEPLER#16]
I changed the convert code in line 56 from

`roberta_sent_encoder = roberta.model.encoder.sentence_encoder`

to

`roberta_sent_encoder = roberta.model.decoder.sentence_encoder`

However another error occurred:

`AttributeError: 'MultiheadAttention' object has no attribute 'k_proj'`

I'm not sure if we should modify the convert code first according to the kepler code and this is the right way to convert.

My transformers version is 2.0.0, and fairseq 0.9.0

**Comment by Bakser** [comment]
Hi, I just tried again and the convert works well on transformers=2.0.0. You need to install the fairseq provided in this repo. The official fairseq does not contain KEPLER implementation.
